default: &default
  adapter: mysql2
  encoding: utf8
  username: roger
  password: D4b2m13
  host: localhost

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
